import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SearchBox from '@/Components/SearchBox/SearchBox.jsx'
import SortMenu from '@/Components//SortMenu/SortMenu.jsx'
import CarCard from '@/Components//CarCard/CarCard.jsx'
const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBox {...props}/>
      <SortMenu/>
      <CarCard/>
    </>
  );
}

export async function getServerSideProps(ctx) {
  const domain = ctx.req.headers["x-forwarded-host"]
    ? ctx.req.headers["x-forwarded-host"]
    : ctx.req.headers.host;
  const res = await fetch(
    `https://api.hillzusers.com/api/dealership/advance/search/vehicles/get/${domain}`
  );
  const searchItem = await res.json();
  return {
    props: { searchItem },
  };
}